"""
CITADEL Core — Domain Models & Type Definitions

Strict Domain-Driven Design (DDD) with Protocol/Interface definitions.
All domain objects are immutable value objects or entities with clear identity.
"""

from __future__ import annotations

import enum
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Protocol, runtime_checkable

import numpy as np
from pydantic import BaseModel, Field, field_validator


# ════════════════════════════════════════════════════════════
#  ENUMERATIONS
# ════════════════════════════════════════════════════════════

class Side(str, enum.Enum):
    BUY = "BUY"
    SELL = "SELL"


class OrderType(str, enum.Enum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"
    STOP_LIMIT = "STOP_LIMIT"
    TRAILING_STOP = "TRAILING_STOP"


class OrderStatus(str, enum.Enum):
    PENDING = "PENDING"
    SUBMITTED = "SUBMITTED"
    PARTIAL_FILL = "PARTIAL_FILL"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class TimeInForce(str, enum.Enum):
    DAY = "DAY"
    GTC = "GTC"
    IOC = "IOC"
    FOK = "FOK"


class AgentAction(str, enum.Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    CLOSE = "CLOSE"
    SCALE_IN = "SCALE_IN"
    SCALE_OUT = "SCALE_OUT"


class KillSwitchLevel(str, enum.Enum):
    L1_SOFT = "L1_SOFT"
    L2_HARD = "L2_HARD"
    L3_NUCLEAR = "L3_NUCLEAR"


class SystemState(str, enum.Enum):
    INITIALIZING = "INITIALIZING"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    L1_RESTRICTED = "L1_RESTRICTED"
    L2_RESTRICTED = "L2_RESTRICTED"
    L3_SHUTDOWN = "L3_SHUTDOWN"
    MAINTENANCE = "MAINTENANCE"
    ERROR = "ERROR"


class EventType(str, enum.Enum):
    # Market Events
    TICK = "TICK"
    BAR = "BAR"
    QUOTE = "QUOTE"
    TRADE = "TRADE"
    # Signal Events
    SIGNAL = "SIGNAL"
    DECISION = "DECISION"
    # Order Events
    ORDER_SUBMITTED = "ORDER_SUBMITTED"
    ORDER_FILLED = "ORDER_FILLED"
    ORDER_CANCELLED = "ORDER_CANCELLED"
    ORDER_REJECTED = "ORDER_REJECTED"
    # Risk Events
    RISK_ALERT = "RISK_ALERT"
    KILL_SWITCH = "KILL_SWITCH"
    # System Events
    HEARTBEAT = "HEARTBEAT"
    AGENT_STATE = "AGENT_STATE"
    SYSTEM_STATE = "SYSTEM_STATE"
    # User Events
    USER_ACTION = "USER_ACTION"
    REPORT_GENERATED = "REPORT_GENERATED"


class Sentiment(str, enum.Enum):
    VERY_BULLISH = "VERY_BULLISH"
    BULLISH = "BULLISH"
    NEUTRAL = "NEUTRAL"
    BEARISH = "BEARISH"
    VERY_BEARISH = "VERY_BEARISH"


# ════════════════════════════════════════════════════════════
#  VALUE OBJECTS (Immutable)
# ════════════════════════════════════════════════════════════

class Tick(BaseModel):
    """Single market tick — immutable value object."""
    symbol: str
    timestamp: datetime
    bid: float
    ask: float
    bid_size: float = 0.0
    ask_size: float = 0.0
    last: float = 0.0
    volume: float = 0.0

    @property
    def mid(self) -> float:
        return (self.bid + self.ask) / 2.0

    @property
    def spread(self) -> float:
        return self.ask - self.bid

    model_config = {"frozen": True}


class Bar(BaseModel):
    """OHLCV bar — immutable value object."""
    symbol: str
    timestamp: datetime
    timeframe: str
    open: float
    high: float
    low: float
    close: float
    volume: float
    vwap: float = 0.0
    trades: int = 0

    model_config = {"frozen": True}


class Signal(BaseModel):
    """Trading signal generated by strategy/agent."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    source: str                    # strategy or agent name
    symbol: str
    action: AgentAction
    confidence: float = Field(ge=0.0, le=1.0)
    size_pct: float = Field(ge=0.0, le=100.0, default=0.0)
    price_target: float | None = None
    stop_loss: float | None = None
    take_profit: float | None = None
    rationale: str = ""
    metadata: dict[str, Any] = Field(default_factory=dict)

    model_config = {"frozen": True}


class Order(BaseModel):
    """Trade order entity with identity."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    signal_id: str = ""
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    symbol: str
    side: Side
    order_type: OrderType = OrderType.MARKET
    quantity: float
    price: float | None = None
    stop_price: float | None = None
    time_in_force: TimeInForce = TimeInForce.DAY
    status: OrderStatus = OrderStatus.PENDING
    filled_quantity: float = 0.0
    filled_price: float = 0.0
    commission: float = 0.0
    slippage: float = 0.0
    broker_order_id: str = ""


class Fill(BaseModel):
    """Order fill record — immutable."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    order_id: str
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    symbol: str
    side: Side
    quantity: float
    price: float
    commission: float = 0.0
    slippage: float = 0.0

    model_config = {"frozen": True}


class Position(BaseModel):
    """Current portfolio position."""
    symbol: str
    side: Side
    quantity: float
    avg_entry_price: float
    current_price: float = 0.0
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0
    open_timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    last_update: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def market_value(self) -> float:
        return self.quantity * self.current_price

    @property
    def cost_basis(self) -> float:
        return self.quantity * self.avg_entry_price

    @property
    def total_pnl(self) -> float:
        return self.unrealized_pnl + self.realized_pnl

    @property
    def pnl_pct(self) -> float:
        if self.cost_basis == 0:
            return 0.0
        return (self.unrealized_pnl / self.cost_basis) * 100.0


class PortfolioSnapshot(BaseModel):
    """Point-in-time portfolio state."""
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    cash: float
    positions: list[Position] = Field(default_factory=list)
    total_equity: float = 0.0
    total_unrealized_pnl: float = 0.0
    total_realized_pnl: float = 0.0
    buying_power: float = 0.0
    gross_exposure: float = 0.0
    net_exposure: float = 0.0
    leverage: float = 0.0
    daily_pnl: float = 0.0


class RiskMetrics(BaseModel):
    """Current risk state snapshot."""
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    system_state: SystemState = SystemState.RUNNING
    portfolio_leverage: float = 0.0
    gross_exposure_pct: float = 0.0
    net_exposure_pct: float = 0.0
    max_single_position_pct: float = 0.0
    daily_pnl_pct: float = 0.0
    weekly_pnl_pct: float = 0.0
    var_95: float = 0.0
    var_99: float = 0.0
    sharpe_ratio: float = 0.0
    sortino_ratio: float = 0.0
    max_drawdown_pct: float = 0.0
    current_drawdown_pct: float = 0.0
    correlation_max: float = 0.0
    active_kill_switches: list[KillSwitchLevel] = Field(default_factory=list)


class NewsArticle(BaseModel):
    """Processed news article."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: datetime
    source: str
    title: str
    summary: str = ""
    content: str = ""
    url: str = ""
    symbols: list[str] = Field(default_factory=list)
    sentiment: Sentiment = Sentiment.NEUTRAL
    sentiment_score: float = 0.0  # -1.0 to 1.0
    relevance_score: float = 0.0  # 0.0 to 1.0
    embedding: list[float] | None = None

    model_config = {"frozen": True}


class AgentDecision(BaseModel):
    """Structured decision from the Tactician agent."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    agent_name: str
    action: AgentAction
    symbol: str
    confidence: float = Field(ge=0.0, le=1.0)
    size_pct: float = Field(ge=0.0, le=100.0, default=0.0)
    rationale: str = ""
    risk_assessment: str = ""
    chain_of_thought: str = ""
    supporting_signals: list[str] = Field(default_factory=list)
    news_context: list[str] = Field(default_factory=list)
    technical_context: dict[str, Any] = Field(default_factory=dict)
    mental_state: str = ""

    model_config = {"frozen": True}


class TrainingResult(BaseModel):
    """Result from nightly LoRA training."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    model_name: str = "lora_adapter"
    training_date: str = ""
    samples_trained: int = 0
    epochs_completed: int = 0
    final_loss: float = 0.0
    duration_s: float = 0.0
    checkpoint_path: str = ""
    metrics_before: dict[str, float] = Field(default_factory=dict)
    metrics_after: dict[str, float] = Field(default_factory=dict)
    drift_detected: bool = False
    drift_score: float = 0.0
    patterns_discovered: list[str] = Field(default_factory=list)
    model_adjustments: list[str] = Field(default_factory=list)
    adapter_path: str = ""


# ════════════════════════════════════════════════════════════
#  EVENT SOURCING
# ════════════════════════════════════════════════════════════

class Event(BaseModel):
    """Base event for Event Sourcing."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    event_type: EventType
    source: str = ""
    payload: dict[str, Any] = Field(default_factory=dict)
    sequence_number: int = 0

    model_config = {"frozen": True}


# ════════════════════════════════════════════════════════════
#  PROTOCOLS (Interface Definitions — DDD)
# ════════════════════════════════════════════════════════════

@runtime_checkable
class DataFeed(Protocol):
    """Interface for market data feeds."""

    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def subscribe(self, symbols: list[str]) -> None: ...
    async def unsubscribe(self, symbols: list[str]) -> None: ...
    async def get_historical_bars(
        self, symbol: str, timeframe: str, start: datetime, end: datetime
    ) -> list[Bar]: ...


@runtime_checkable
class BrokerGateway(Protocol):
    """Interface for broker connections."""

    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def submit_order(self, order: Order) -> Order: ...
    async def cancel_order(self, order_id: str) -> bool: ...
    async def get_positions(self) -> list[Position]: ...
    async def get_account_info(self) -> dict[str, Any]: ...
    async def get_order_status(self, order_id: str) -> OrderStatus: ...


@runtime_checkable
class Strategy(Protocol):
    """Interface for trading strategies."""

    @property
    def name(self) -> str: ...

    async def on_bar(self, bar: Bar) -> list[Signal]: ...
    async def on_tick(self, tick: Tick) -> list[Signal]: ...
    def reset(self) -> None: ...


@runtime_checkable
class RiskManager(Protocol):
    """Interface for risk management."""

    def check_order(self, order: Order, portfolio: PortfolioSnapshot) -> tuple[bool, str]: ...
    def check_portfolio(self, portfolio: PortfolioSnapshot) -> list[KillSwitchLevel]: ...
    def get_metrics(self) -> RiskMetrics: ...


@runtime_checkable
class LLMEngine(Protocol):
    """Interface for LLM inference engines."""

    async def generate(self, prompt: str, max_tokens: int = 4096) -> str: ...
    async def generate_stream(self, prompt: str, max_tokens: int = 4096): ...
    def get_device_info(self) -> dict[str, Any]: ...
    async def warmup(self) -> None: ...


@runtime_checkable
class Agent(Protocol):
    """Interface for system agents."""

    @property
    def name(self) -> str: ...

    @property
    def is_alive(self) -> bool: ...

    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def heartbeat(self) -> bool: ...


@runtime_checkable
class EventStore(Protocol):
    """Interface for event persistence."""

    async def append(self, event: Event) -> None: ...
    async def get_events(
        self,
        event_type: EventType | None = None,
        start: datetime | None = None,
        end: datetime | None = None,
        limit: int = 1000,
    ) -> list[Event]: ...
    async def replay(self, start: datetime, end: datetime) -> list[Event]: ...


@runtime_checkable
class ReportGenerator(Protocol):
    """Interface for report generation."""

    async def generate_daily_report(self, date: str | None = None) -> str: ...
    async def generate_custom_report(self, sections: list[str]) -> str: ...
    async def email_report(self, report_path: str) -> bool: ...


# ════════════════════════════════════════════════════════════
#  SHARED MEMORY STRUCTURES (NumPy-compatible)
# ════════════════════════════════════════════════════════════

# Tick buffer dtype for shared memory ring buffer
TICK_DTYPE = np.dtype([
    ("timestamp_ns", np.int64),
    ("symbol_hash", np.uint64),     # FNV-1a hash of symbol
    ("bid", np.float64),
    ("ask", np.float64),
    ("bid_size", np.float64),
    ("ask_size", np.float64),
    ("last", np.float64),
    ("volume", np.float64),
])

# Signal buffer dtype
SIGNAL_DTYPE = np.dtype([
    ("timestamp_ns", np.int64),
    ("source_hash", np.uint64),
    ("symbol_hash", np.uint64),
    ("action", np.int8),            # Maps to AgentAction
    ("confidence", np.float32),
    ("size_pct", np.float32),
    ("price_target", np.float64),
    ("stop_loss", np.float64),
])

# Risk flags dtype
RISK_DTYPE = np.dtype([
    ("timestamp_ns", np.int64),
    ("system_state", np.int8),
    ("leverage", np.float32),
    ("gross_exposure_pct", np.float32),
    ("net_exposure_pct", np.float32),
    ("daily_pnl_pct", np.float32),
    ("var_95", np.float32),
    ("kill_switch_flags", np.uint8),  # bitfield
])

# Portfolio state dtype
PORTFOLIO_DTYPE = np.dtype([
    ("timestamp_ns", np.int64),
    ("cash", np.float64),
    ("total_equity", np.float64),
    ("unrealized_pnl", np.float64),
    ("realized_pnl", np.float64),
    ("daily_pnl", np.float64),
    ("num_positions", np.int32),
    ("leverage", np.float32),
])


def symbol_hash(symbol: str) -> int:
    """FNV-1a 64-bit hash for symbol lookups in shared memory."""
    h = 0xCBF29CE484222325
    for byte in symbol.encode():
        h ^= byte
        h = (h * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return h
